[package]
name = "ping"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ping"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

ping_integrity = { workspace = true } 
